// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrxmAg9sJk92UbDO_eb2xBG3GMr3UR4fI',
    appId: '1:50398244024:web:298a48eea11c709b9c184d',
    messagingSenderId: '50398244024',
    projectId: 'shopeasy-a7380',
    authDomain: 'shopeasy-a7380.firebaseapp.com',
    storageBucket: 'shopeasy-a7380.appspot.com',
    measurementId: 'G-GWK5LR7LF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmM7iZiwPGN_vTZ2B8YRgVDX-zzx6jAWM',
    appId: '1:50398244024:android:9e070fd4b09e5ecc9c184d',
    messagingSenderId: '50398244024',
    projectId: 'shopeasy-a7380',
    storageBucket: 'shopeasy-a7380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vwhjj2RFvPPK8TgyswQZOENCr_-dw6s',
    appId: '1:50398244024:ios:659f438e3e26e17e9c184d',
    messagingSenderId: '50398244024',
    projectId: 'shopeasy-a7380',
    storageBucket: 'shopeasy-a7380.appspot.com',
    androidClientId: '50398244024-2a69apqcsm15pa7s9omgcapcaqgu1usg.apps.googleusercontent.com',
    iosClientId: '50398244024-rf7df199s939aqhlj38l1qvl8vi7rm24.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopeasyGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vwhjj2RFvPPK8TgyswQZOENCr_-dw6s',
    appId: '1:50398244024:ios:659f438e3e26e17e9c184d',
    messagingSenderId: '50398244024',
    projectId: 'shopeasy-a7380',
    storageBucket: 'shopeasy-a7380.appspot.com',
    androidClientId: '50398244024-2a69apqcsm15pa7s9omgcapcaqgu1usg.apps.googleusercontent.com',
    iosClientId: '50398244024-rf7df199s939aqhlj38l1qvl8vi7rm24.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopeasyGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrxmAg9sJk92UbDO_eb2xBG3GMr3UR4fI',
    appId: '1:50398244024:web:b9437b3d6746e56f9c184d',
    messagingSenderId: '50398244024',
    projectId: 'shopeasy-a7380',
    authDomain: 'shopeasy-a7380.firebaseapp.com',
    storageBucket: 'shopeasy-a7380.appspot.com',
    measurementId: 'G-L3BGK6LWM2',
  );

}